name: Build and deploy container app to Azure Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: npm install, and build
      run: |
        npm install
        npm run build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_d4b2b10559ce43228bcd08935183545a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_22b99d87e4df46a3b2ec4f0660b2d7d0 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4b2b10559ce43228bcd08935183545a }}/${{ secrets.DOCKER_IMAGE }}:front
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'catphish'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bbe66bf86c984219824dd6b09f6b2acb }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d4b2b10559ce43228bcd08935183545a }}/${{ secrets.DOCKER_IMAGE }}:front'
